### ISSUE TITLE
Accessibility - a11y report and dark mode

### ISSUE THREAD

**Issue by casserole27** [casserole27/hikefinder#47]
- change green color based on [a11y report](https://wave.webaim.org/report#/https://www.clewisdev.com/hikefinder/index.html)
- change copyright text size

Dark mode
```css
/*====== DARK MODE PREFERENCE ======*/

@media (prefers-color-scheme: dark) {
    :root {
        --bg: #222;
        --white-lg: #333;
        --white: #555           ;
        --lt-gray: #000;
    }

    .saved-heading {
        color: white;
    }
}
```
